version: '2'

services:
    reverseproxy:
        image: alchoholly/nginx-for-easycrm
        ports:
            - 8090:8090
        restart: always

    easycrm:
        depends_on:
            - reverseproxy
        image: alchoholly/easycrm # or change this to your EasyCRM image name
        restart: always
